
          <td background="images/point.gif" width="4" bgcolor="ffffff"><img src="images/1p.gif" width="4" height="1"></td>
          <td valign="top" width="216" bgcolor="ffffff">
            <table height=19 border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr height=28>
              <td width=4%> </td>
              <td width=6></td>
              <td align=center valign=center bgcolor="ffffff" class=white>
               <span style="font-size:10pt"><font color="3879B3" face="Tahoma">

              <b></b> </span></font>    </td>
            </tr>
          </table>

      <table width="188" height="200" border="0">
     <tr>
       <td>&nbsp;</td>
     </tr>
     </table>

           <table width="100%" height=28 border="0" cellspacing="0" cellpadding="0">
              <tr height=19>
                <td width=4%> </td>
                <td width=6></td>
                <td class=white bgcolor="ffffff" align=center valign=center>
                <span style="font-size:10pt"><font color="3879B3" face="Tahoma">

                <b>ТОВАРЫ НЕДЕЛИ</b></span></font> </td>
              </tr>
            </table>

<!-- BEGIN list -->
            <table width="100%" border="0" cellspacing="0" cellpadding="6">
              <tr bgcolor="#FFFFFF">
                <td width="15"><img src="images/{count}.gif" alt="{name}" width="15" height="15"></td>
                <td class=sm><a href="index.php?id={id}" class="b">{name} {model} <!-- BEGIN price_list --> - {price} руб.<!-- END price_list --></a></td>
              </tr>
            </table>

            <!-- END list -->



            <!-- BEGIN no_list -->
            <table width="100%" border="0" cellspacing="0" cellpadding="6">
              <tr bgcolor="#FFFFFF">
                <td width="15"><img src="images/1p.gif" width="15" height="15"></td>
                <td class=sm></a></td>
              </tr>
            </table>
<!-- END no_list -->

         </td>








            <!--<table width="100%" border="0" cellspacing="0" cellpadding="0">
          <td width="1" bgcolor="DDDDDD"><img src="images/1p.gif" width="1" height="1"></td>
              <tr>
                <td bgcolor="#FFFFFF"><img src="images/1p.gif" width="1" height="2"></td>
              </tr>
                <td align="center">
                <a href="http://www.shedevr.ru/index.php?op=specpr">
                <img src="/KrujkaThermos.jpg" width="191" height="230" border="0" alt="Специальная акция"></a>
                </td>
             <tr>
                <td bgcolor="#FFFFFF"><img src="images/1p.gif" width="1" height="2"></td>
              </tr>
              <tr>
                <td background="images/wtrihback.gif"><img src="images/1p.gif" width="1" height="12"></td>
              </tr>
            </table>
          </td>-->