                  </td>
          <td background="images/point.gif" width="4" bgcolor="ffffff"><img src="images/1p.gif" width="4" height="1"></td>

          <td valign="top" width="216" bgcolor="ffffff">

<!-- BEGIN spec -->
            <table width="100%" height=19 border="0" cellspacing="0" cellpadding="0">
              <tr height=19>

                <td class=white align=center valign=center>
                <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                <b>ПОДАРКИ</b>
                </font></span>
                </td>
              </tr>
            </table>

<!-- BEGIN list_spec -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
            </table>
            <table width="190" border="0" cellspacing="0" cellpadding="2" align="center">
              <tr>
                <td class=tb>
                                  <a href="index.php?id={id}" class=maing>{name}</a>&nbsp;&nbsp;

                                </td>
              </tr>
              <tr>
                <td valign="top">
                                  <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                </td>
              </tr>
              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
              <tr>
                <td class=green nowrap><span style="font-size:8pt"><font color="666666" face="Tahoma"><b>{price} руб.</b></font></span></td>
              </tr>

              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="3" background="images/point3.gif" bgcolor="#ffffff" height="1"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>
<!-- END list_spec -->

            <table width="100%" border="0" cellspacing="0" cellpadding="5">
              <!-- <tr>
                <td class=smb bgcolor="F0F0F0">&nbsp;&nbsp;<a href="index.php?op=spec" class=b>все спецпредложения</a></td>
              </tr> -->
            </table>
<!-- END spec -->


<!-- BEGIN season -->
            <table width="99%" border="0" cellspacing="0" cellpadding="4" align=center>
              <tr>
                <td bgcolor="#ffffff" height=2></td>
              </tr>
            </table>
            <table width="100%" height=19 border="0" cellspacing="0" cellpadding="0">
              <tr height=19>


                <td class=white bgcolor="ffffff" align=center valign=center>
                <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                <b>ХИТЫ ПРОДАЖ</b>
                </font></span>
                </td>
              </tr>
            </table>

<!-- BEGIN list_season -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
            </table>
            <table width="190" border="0" cellspacing="0" cellpadding="2" align="center">

              <tr>
                <td class=tb>
                                  <a href="index.php?id={id}" class=maing>{name}</a>&nbsp;&nbsp;
                  <a href="index.php?id={id}" class=r><img src="images/arrow_red.gif" width="7" height="7" border="0"></a>
                                </td>
              </tr>
              <tr>
                <td valign="top">
                                  <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                </td>
              </tr>
              <tr>
                <td class=green><span style="font-size:8pt"><font color="666666" face="Tahoma"><b>{price} руб.</b></font></span></td>
              </tr>

                          <tr>
                                <td><img src="images/1p.gif" width="1" height="10"></td>
                          </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="3" background="images/point3.gif" bgcolor="#ffffff" height="1"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>
<!-- END list_season -->

            <table width="100%" border="0" cellspacing="0" cellpadding="0">
           <!--   <tr>
                <td class=smb bgcolor="F0F0F0">&nbsp;&nbsp;<a href="index.php?op=season" class=b> <!--все новинки--> </a></td>
              </tr>
            </table>
<!-- END season -->


<!-- BEGIN news -->
            <table width="99%" border="0" cellspacing="0" cellpadding="4" align=center>
              <tr>
                <td bgcolor="#ffffff" height=2></td>
              </tr>
            </table>
            <table width="100%" height=19 border="0" cellspacing="0" cellpadding="0">
              <tr height=19>

                <td class=white bgcolor="ffffff" align=center valign=center><b>
               <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                Горячие предложения</b>
                </font></span>
                </td>
              </tr>
            </table>
<!-- BEGIN list_news -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
            </table>
            <table width="190" border="0" cellspacing="0" cellpadding="2" align="center">
              <tr>
                <td class=tb>
                                  <a href="index.php?id={id}" class=maing>{name}</a>&nbsp;&nbsp;
                                    </td>
              </tr>
              <tr>
                <td valign="top">
                                  <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                </td>
              </tr>
                          <tr>
                <td class=green><span style="font-size:8pt"><font color="666666" face="Tahoma"><b>{price} руб.</b></font></span></td>
              </tr>

                          <tr>
                                <td><img src="images/1p.gif" width="1" height="10"></td>
                          </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="3" background="images/point3.gif" bgcolor="#ffffff" height="1"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>
<!-- END list_news -->

            <table width="100%" border="0" cellspacing="0" cellpadding="5">
              <tr>
                                <td class=smb bgcolor="ffffff">&nbsp;&nbsp;<a class=maing href="index.php?op=new" class=b><!--все подарки--></a></td>
                          </tr>
            </table>
<!-- END news -->

          </td>