           <div class=title>Статистика посещений категорий </div>
<hr><br>
<center><span style="font-size:10pt"><font face="Tahoma">Список категорий товаров</font></span></center>
<table border="0" cellpadding="0" cellspacing="0" width="50%" align=center>
  <tr>
        <td class=tb bgcolor="000000">
 <table border="0" cellpadding="4" cellspacing="1" width="100%">
  <!-- BEGIN list_cat -->
  <tr>
        <td class=tb bgcolor="f2f2f2">
   <b>>>>&nbsp;</b><a href=index.php?op=allstat&mode=statistic&pid={id}>{name}</a><br>
  </td>
  </tr>
 <!-- END list_cat -->
  </table>

        </td>
  </tr>
</table>
