<HTML>
<table width="80%" border="1">
    <tr>
      <td width="100%">Email:<font color="red">shop@shedevr.ru</font></td>
      <td width="100%">php7.2 <font color="red">OK </td>
    </tr>
    <tr>
      <td width="100%">Login:<font color="red">1</font></td>
<!-- BEGIN u_sess -->
      <td><font color="green">{user1}</td>
    </tr>
    <tr>
      <td>Password:<font color="red">1</font></td>
      <td><font color="green">{pw1}
<!-- END u_sess -->
<br>
