 <div class=title>Статистика посещений</div>
 <hr><br><br><br><br>
 <table cellspacing=0 cellpadding=1 border=0 width=60% align=center>
<tr>
<td valign=top class=t bgcolor="999999">
<table cellspacing=0 cellpadding=0 border=0 width=100%>
<tr>
<td valign=top class=t bgcolor="ffffff" align=center><br>

<span style="font-size:16pt;"><b><font color="black">Количество посетителей страницы</font></b></span>
<span style="font-size:16pt;"><b><font color="red"> {con}</font></b></span>
<br><br>

</td></tr></table>
 </td></tr></table>