 <table width="100%" border="0" cellspacing="0" cellpadding="0" align=center>
              <tr>
                <td><br>
                <div class=title>Редактирование FAQ</div>
                <hr>
                </td>
              </tr>
            </table>
            <br>
 <table width="95%" border="0" cellspacing="0" cellpadding="0" align=center>
              <tr>
                <td>
  <hr color="cccccc" size=1 noshade>
  <!-- BEGIN list_catfaq -->
  <span style="font-size:9pt"><font face="Verdana" color="000000"><b>&bull;&nbsp;<a href="index.php?op=faqcatalog&page=1&cat={id}">{name}</a></b></span></font><br>
  <!-- END list_catfaq -->
  <!-- BEGIN no_list_catfaq -->
  <center><span style="font-size:9pt"><font face="Verdana" color="000000"><b>Нет категорий с FAQ</span></font></center><br>
  <!-- END no_list_catfaq -->


    <hr color="cccccc" size=1 noshade>
                </td>
                </tr>


                </table>