           <div class=title>Статистика посещений  </div>
<hr><br>
 <table cellspacing=0 cellpadding=1 border=0 width=100% align=center>
<tr>
<td valign=top class=t bgcolor="999999">
<table cellspacing=0 cellpadding=0 border=0 width=100%>
<!-- BEGIN list -->
<tr>
<td valign=top class=t bgcolor="ffffff">




<span style='font-size:10pt;'><font color='000000' face='Tahoma'>{ip}</font></span><br>
 </td></tr>

<!-- END list -->
<!-- BEGIN no_ip -->

<tr>
<td valign=top class=t bgcolor="ffffff" align=center><br>
<span style='font-size:12pt;'><font color='000000' face='Tahoma'>Нет посетителей :(</font></span><br>
</td></tr>
<!-- END no_ip -->

</table>
 </td></tr></table><br>
 <center><a href=index.php?op=fcc&mode=del>Удалить</a></center>