 <table width="100%" border="0" cellspacing="0" cellpadding="0" align=center>
              <tr>
                <td><br>
                <div class=title>Операции над ссылками</div>
                <hr>
                </td>
              </tr>
            </table>
            <br>
 <table width="95%" border="0" cellspacing="0" cellpadding="0" align=center>
              <tr>
                <td>
  <hr color="cccccc" size=1 noshade>
  <!-- BEGIN list_cat -->
  <span style="font-size:9pt"><font face="Verdana" color="000000"><b>&bull;&nbsp;<a href="index.php?op=linkscatalog&page=1&idcat={idcat}">{namecat}</a></b></span></font><br>
  <!-- END list_cat -->
    <hr color="cccccc" size=1 noshade>
                </td>
                </tr>
   <tr>
                <td align=center><br>
     
          </td></tr>

                </table>