<table width="100%" border="0" cellspacing="0" cellpadding="0" align=center>
              <tr>
                <td><br>
                <div class=title>Быстрое редактирование товаров (код, цена)</div>
                <hr>
                </td>
              </tr>
            </table>



              <br><br>


    <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
              <tr>
                <td align="left">
<!-- BEGIN list_items_cat1 -->
                <font class=nameglav><a href="index.php?op=select&mode=listselect&id={id}">{name}</a></font>
<br>
<!-- END list_items_cat1 -->

                </td>
              </tr>
             </table><br>
