<head>
<title>Admin login</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251"><meta http-equiv="Content-Language" content="ru">
<LINK rel='stylesheet' type='text/css' href='style.css'>
</head>

<body bgcolor='#F6F6F6' onLoad="document.form.username.focus()">
<br><br>

<form name=form action=index.php method=post>

<table cellpadding=0 cellspacing=1 width=400 align=center border=0>

<tr>
  <td colspan="2" bgcolor="#CCCCCC"><img src="images/1p.gif" width="1" height="2"></td>
</tr>

<tr>
<td width=150 height=30><font size=2>Username :</font></td>
<td width=250  height=30 align=center><input type=text name=username></td>
</tr>

<tr>
  <td colspan="2" bgcolor="#CCCCCC"><img src="images/1p.gif" width="1" height="2"></td>
</tr>

<tr>
<td height=30><font size=2>Password :</font></td>
<td align=center><input type=password name=password></td>
</tr>

<tr>
  <td colspan="2" bgcolor="#CCCCCC"><img src="images/1p.gif" width="1" height="2"></td>
</tr>

<tr>
  <td align=center colspan=2><input type=submit value=" Login " class=t></td>
</tr>
</table>

</form>

</body>
</html>
