<!-- BEGIN spec_pred_nah -->
            <table width="100%" border="0" cellspacing="0" cellpadding="4" height="27">
              <tr>
                <td bgcolor="D30000" class=white align="center">&nbsp;&nbsp;&nbsp;ВСЕ НА ПИКНИК!</td>
              </tr>
            </table>

            <table width="383" border="0" cellspacing="0" cellpadding="0">

<!-- BEGIN main_second -->
              <tr>

<!-- BEGIN list_spec1 -->

                <td width="191" valign=top>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                        <table width="170" border="0" cellspacing="0" cellpadding="2" align="center">
                    <tr>
                      <td class=tb>
                                                <a href="index.php?id={items}" class=r>{name} {mark}</a>&nbsp;
                                                <a href="index.php?id={items}" class=r><img src="images/arrow_red.gif" width="7" height="7" border="0"></a></td>
                    </tr>
                    <tr>
                      <td valign="top">
                                                <a href="index.php?id={items}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                          </td>
                                        </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                                        <tr>
                      <td class=green nowrap>{price} руб.</td>
                    </tr>
              <tr>
                <td class=sm>{description}</td>
              </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                  </table>

                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>

<!-- END list_spec1 -->
<!-- BEGIN no_list_spec1 -->
                <td width="191">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END no_list_spec1 -->

                <td bgcolor="DCDDDC"><img src="images/1p.gif" width="1" height="1"></td>

<!-- BEGIN list_spec2 -->
                <td width="191" valign=top>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                        <table width="170" border="0" cellspacing="0" cellpadding="2" align="center">
                    <tr>
                      <td class=tb>
                                                <a href="index.php?id={items}" class=r>{name} {mark}</a>&nbsp;
                                                <a href="index.php?id={items}" class=r><img src="images/arrow_red.gif" width="7" height="7" border="0"></a>
                                          </td>
                    </tr>
                    <tr>
                      <td valign="top">
                                                <a href="index.php?id={items}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                          </td>
                                        </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                                        <tr>
                      <td class=green nowrap>{price} руб.</td>
                    </tr>
              <tr>
                <td class=sm>{description}</td>
              </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                  </table>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END list_spec2 -->
<!-- BEGIN no_list_spec2 -->
                <td width="191">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END no_list_spec2 -->
              </tr>

              <tr>
                <td colspan="3" bgcolor="DCDDDC"><img src="images/1p.gif" width="1" height="1"></td>
              </tr>
<!-- END main_second -->
              <!--<tr>
                <td colspan="3">
                  <table width="100%" border="0" cellspacing="0" cellpadding="5">
                    <tr>
                      <td class=smb bgcolor="F0F0F0">&nbsp;&nbsp;<a href="index.php?op=spec" class=b>все спецпредложения </a></td>
                    </tr>
                  </table>
                </td>
              </tr>
              <tr>
                <td colspan="3" bgcolor="DCDDDC"><img src="images/1p.gif" width="1" height="1"></td>
              </tr>-->
            </table>
<!-- END spec_pred_nah -->


            <table width="383" border="0" cellspacing="0" cellpadding="0">

              <tr>
                <td width="191">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0" height="27">
                    <tr>
                      <td bgcolor="D30000" class=white align="left"><!--<a href="index.php?op=new" class=w style="text-decoration:none">-->&nbsp;&nbsp;
НОВИНКИ</a></td>
                    </tr>
                  </table>
                </td>
<td bgcolor="FFFFFF"><img src="images/1p.gif" width="1" height="1"></td>

                                <td width="191">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0" height="27">
                    <tr>
                      <td bgcolor="D30000" class=white align="left"><!--<a href="index.php?op=new" class=w style="text-decoration:none">-->
&nbsp;&nbsp;&nbsp;ХИТЫ ПРОДАЖ</a></td>
                    </tr>
                  </table>
                </td>
              </tr>


<!-- BEGIN main_first -->
              <tr>
<!-- BEGIN list_new -->
                <td valign=top>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                        <table width="170" border="0" cellspacing="0" cellpadding="2" align="center">
                    <tr>
                      <td class=tb>
                                                <a href="index.php?id={id}" class=r>{name} {mark}</a>&nbsp;<a href="index.php?id={id}" class=r><img src="images/arrow_red.gif" width="7" height="7" border="0"></a>
                                          </td>
                    </tr>
                    <tr>
                      <td valign="top">
                                                <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                          </td>
                                        </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                                        <tr>
                      <td class=green nowrap>{price} руб.</td>
                    </tr>
              <tr>
                <td class=sm>{description}</td>
              </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                  </table>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END list_new -->
<!-- BEGIN no_list_new -->
                <td>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END no_list_new -->


                <td bgcolor="DCDDDC"><img src="images/1p.gif" width="1" height="1"></td>

<!-- BEGIN list_season -->
                <td valign=top>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                        <table width="170" border="0" cellspacing="0" cellpadding="2" align="center">
                    <tr>
                      <td class=tb>
                                                <a href="index.php?id={id}" class=r>{name} {mark}</a>&nbsp;
                                                <a href="index.php?id={id}" class=r><img src="images/arrow_red.gif" width="7" height="7" border="0"></a></td>
                    </tr>
                    <tr>
                      <td valign="top">
                                                <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                          </td>
                                        </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                                        <tr>
                      <td class=green nowrap>{price} руб.</td>
                    </tr>
              <tr>
                <td class=sm>{description}</td>
              </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                  </table>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END list_season -->
<!-- BEGIN no_list_season -->
                <td>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END no_list_season -->

              </tr>
              <tr>
                <td colspan="3" bgcolor="DCDDDC"><img src="images/1p.gif" width="1" height="1"></td>
              </tr>
<!-- END main_first -->

              <tr>
                <td class=smb>
                  <table width="100%" border="0" cellspacing="0" cellpadding="5">
                    <tr>
                      <td class=smb bgcolor="F0F0F0">&nbsp;&nbsp;<a href="index.php?op=new" class=b>все подарки</a></td>
                    </tr>
                  </table>

                </td>
                <td bgcolor="F0F0F0"><img src="images/1p.gif" width="1" height="1"></td>
                <td class=smb>
                  <table width="100%" border="0" cellspacing="0" cellpadding="5">
                    <tr>
                     <td class=smb bgcolor="F0F0F0">&nbsp;&nbsp;<a href="index.php?op=season" class=b><!--все товары зимнего сезона--></a></td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>