<!--  <div style="width: 100%; position: fixed; top: 0px; left: 0px;"> -->
  <div style="width: 100%; top: 0px; left: 0px;">
    <table width="100%" cellspacing="0" cellpadding="0" border="0" style="border: 1px outset white;">
      <tr>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=orders" class=navi><img src="images/orders.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=orders" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=orders" class=navi>Заказы</a></td>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=catalog" class=navi><img src="images/catalog.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=catalog" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=catalog" class=navi>Каталог</a></td>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=item" class=navi><img src="images/item.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=item" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=item" class=navi>Товары</a></td>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=users" class=navi><img src="images/users.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=users" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=users" class=navi>Клиенты</a></td>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=cms&parent=1" class=navi><img src="images/cms.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=cms&parent=1" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=cms&parent=1" class=navi>Страницы</a></td>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=spec" class=navi><img src="images/money.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=spec" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=spec" class=navi>Спец.предлож</a></td>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=admin" class=navi><img src="images/admin.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=admin" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=admin" class=navi>Операторы</a></td>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=reference" class=navi><img src="images/reference.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=reference" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=reference" class=navi>Справочники</a></td>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=settings" class=navi><img src="images/setting.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=settings" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=settings" class=navi>Настройки</a></td>
        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>



        <td class="navi" nowrap="nowrap" width=100% align=right><a href="index.php?op=logout" class=navi>Выход</a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=logout" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=logout" class=navi><img src="images/exit.gif" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="15" height="22" alt="" border="0"></td>


      </tr>
    </table>




  </div>
  <table width="100%" cellspacing="0" cellpadding="0" border="0" style="border: 1px outset white;">
      <tr>
  <td class="navi" nowrap="nowrap" width=3 height=16></td>
        <td class="navi" nowrap="nowrap" align=left><a href="index.php?op=select&mode=listcatalog" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap" align=left>|&nbsp;<a href="index.php?op=select&mode=listcatalog" class=navi>Редактирование кода и цен</a>&nbsp;|&nbsp;
        <a href="index.php?op=linkscatalog" class=navi>Операции над ссылками</a>&nbsp;|&nbsp;
        <a href="index.php?op=addlink" class=navi>Добавление ссылок</a>&nbsp;|

        <a href="index.php?op=faqcatalog" class=navi>Редактирование FAQ</a>&nbsp;|
        <a href="index.php?op=starting&action=list" class=navi>Назначение скидки</a>&nbsp;|
        <a href="index.php?op=client_add" class=navi>Добавление клиентов</a>&nbsp;|
        </td>


      </tr></table>

      <table width=100% cellpadding=15 cellspacing=0 border=0>
  <tr>
        <td>
