<!--  <div style="width: 100%; position: fixed; top: 0px; left: 0px;"> -->
  <div style="width: 100%; top: 0px; left: 0px;">
    <table width="100%" cellspacing="0" cellpadding="0" border="0" style="border: 1px outset white;">
      <tr>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=orders" class=navi><img src="images/orders.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=orders" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=orders" class=navi>Заказы</a></td>

        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="10" height="22" alt="" border="0"></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=users" class=navi><img src="images/users.gif" width=16 height=16 alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=users" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=users" class=navi>Клиенты</a></td>

        <td class="navi" nowrap="nowrap" width=100% align=right><a href="index.php?op=logout" class=navi>Выход</a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=logout" class=navi><img src="images/1p.gif" width="5" height="22" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><a href="index.php?op=logout" class=navi><img src="images/exit.gif" alt="" border="0"></a></td>
        <td class="navi" nowrap="nowrap"><img src="images/1p.gif" width="15" height="22" alt="" border="0"></td>


      </tr>
    </table>
  </div>
  
<table width=100% cellpadding=15 cellspacing=0 border=0>
  <tr>
	<td>
