<div class=title>Справочники</div>
<hr>

<table cellspacing=0 cellpadding=0 border=0 width=100%>
  <tr>
	<td valign=top class=t>

<p class=th>Список доступных справочников</p>
<table border="1" cellpadding="2" cellspacing="2" width=100% bgcolor="#F0F0F0" bordercolor="#000000" style="border-collapse: collapse;">
<tr><td>
  <table cellpadding=5>
	<tr>
	  <td class=tb><a href=index.php?op=reference&db=svva>Свойства товара</a></td>
	  <td class=tb> | </td>
	  <td class=tb><a href=index.php?op=reference&db=statu>Статусы товара</a></td>
	  <td class=tb> | </td>
	  <td class=tb><a href=index.php?op=reference&db=items_ref>Тех. характеристики товара</a></td>
	  <td class=tb> | </td>
	  <td class=tb><a href=index.php?op=reference&db=vendor>Производители</a></td>
	  <td class=tb> | </td>
	  <td class=tb><a href=index.php?op=reference&db=links></a></td>
	</tr>
  </table>
</td></tr>
</table>

<br><br>
