<div class=title>Настройки магазина
<!-- BEGIN update -->
<font class=warning>(Данные обновлены)</font>
<!-- END update -->
</div>
<hr>
<table>
<!-- BEGIN list -->
  <form action="index.php" method="POST">
  <input type="hidden" name="op" value="settings">
  <input type="hidden" name="id" value="{id}">
  <tr>
	<td class="tb" align="right">{text}: </td>
	<td class="t"><input type="text" name="value" value="{value}" style="width:200px;" class="t"></td>
	<td class="t"><input type="submit" value="Обновить настройки"></td>
  </tr>
  </form>
<!-- END list -->
</table>

