            <table width="100%" border="0" cellspacing="0" cellpadding="4" height="27" align=center>
              <tr>
                <td bgcolor="F0F0F0" class=sm>&nbsp;&nbsp;{termometr}</td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="DFDFDF"><img src="images/1p.gif" width="1" height="1" alt="биотуалет, бензиновая лампа, керосиновая лампа, туристическое снаряжение"></td>
              </tr>
            </table>

            <table width="100%" border="0" cellspacing="0" cellpadding="10">
              <tr>
                <td><h2>{title}</h2></td>
              </tr>
              <tr>
                <td class=sm>{text}</td>
              </tr>
            </table>

<!-- BEGIN list_hidden -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>
                <td width=25> </td>
                <td width=9><img src=images/p1_l.gif width=9 height=19></td>
                <td bgcolor="003E76" class=white align="center">ДРУГИЕ СТАТЬИ РАЗДЕЛА</td>
                <td width=9><img src=images/p1_r.gif width=9 height=19></td>
                <td width=25> </td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><img src="images/1p.gif" width="1" height="1"  alt="биотуалет, бензиновая лампа, керосиновая лампа, туристическое снаряжение"></td>
              </tr>
              <tr>
                <td bgcolor="479680"><img src="images/1p.gif" width="1" height="1"  alt="биотуалет, бензиновая лампа, керосиновая лампа, туристическое снаряжение"></td>
              </tr>
            </table>
<!-- BEGIN list_other -->
            <table width="100%" border="0" cellspacing="0" cellpadding="7">
              <tr>
                <td class=sm><img src="images/arrow_green.gif" width="7" height="7">
                  &nbsp;&nbsp;<a href="index.php?op={url}" class=b>{title}</a></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="DFDFDF"><img src="images/1p.gif" width="1" height="1"  alt="биотуалет, бензиновая лампа, керосиновая лампа, туристическое снаряжение"></td>
              </tr>
            </table>
<!-- END list_other -->
<!-- END list_hidden -->