 <table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>
                <td width=25> </td>
                <td width=9><img src=images/p1_l.gif width=9 height=19></td>
                <td bgcolor="003E76" class=white align="center">НАШИ СКИДКИ</td>
                <td width=9><img src=images/p1_r.gif width=9 height=19></td>
                <td width=25> </td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="#ffffff" height=2></td>
              </tr>
              <tr>
                <td background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
            </table>



<center><span style="font-size:14pt"><font face="Tahoma">Уважаемые господа!</font></span>
<br>
<span style="font-size:10pt"><font face="Tahoma">Специально для Вас мы разработали систему скидок:</font></span></center>
<br><br>
<table width="96%" border="0" cellspacing="0" cellpadding="0" align="center">

              <tr>
                <td bgcolor="#ffffff">
                  <table width="100%" border="0" cellspacing="1" cellpadding="3">

                    <tr bgcolor="#0099cc">
                      <td width="24%" class=smb align="center">Сумма покупки</td>
                      <td width="24%" class=smb align="center">От 15000.00 руб</td>
                       <td width="24%" class=smb align="center">От 25000.00 руб</td>
                       <td width="24%" class=smb align="center">Свыше 30000.00 руб</td>

                     </tr>
                     </table>
                     </td></tr>
                     </table>

                     <table width="96%" border="0" cellspacing="0" cellpadding="0" align="center">

              <tr>
                <td bgcolor="#0099cc">
                  <table width="100%" border="0" cellspacing="1" cellpadding="3">

                      <tr bgcolor="ffffff">
                      <td class=smb width="24%" align="center">Скидка %</td>
                      <td class=smb width="24%" align="center"><b>3 %</b></td>
                       <td class=smb width="24%" align="center"><b>7 %</b></td>
                       <td class=smb width="24%" align="center"><b>10 %</b></td>
                     </tr>
                     </table>
                     </td></tr>
                     </table>
    <table width="96%" border="0" cellspacing="0" cellpadding="0" align="center">
              <tr>
                <td bgcolor="#ffffff" align=center>
    <br><hr color=cccccc size=1 noshade>
   <br><span style="font-size:10pt"><font face="Tahoma">
                     Надеемся Вы останетесь довольны нашим сервисом и ценами.
                     </font></span>
  <br>

  <form action-index.php method=GET>
  <input type=hidden name=op value=cart>
    <hr color=cccccc size=1 noshade>
  <input type=submit name=submit value="Вернуться в корзину">
    <hr color=cccccc size=1 noshade>
  </form>

                     </td></tr>
                     </table>