            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>

                <td bgcolor="ffffff" class=white align="center">
                 <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                <b>ВХОД В МАГАЗИН</b></font></span></td>

              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="#ffffff" height=2></td>
              </tr>
              <tr>
                <td background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="20">
              <tr>
                <td class=sm align="center">НОВЫЙ ПОЛЬЗОВАТЕЛЬ? <a href="index.php?op=newreg" class=maing><b>Зарегистрироваться</b></a></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="20">
              <tr>
                <td class=sm align="center">ВХОД ДЛЯ ЗАРЕГИСТРИРОВАННЫХ ПОЛЬЗОВАТЕЛЕЙ:</td>
              </tr>
            </table>
            <table width="250" border="0" cellspacing="0" cellpadding="0" align="center">
              <tr>
                <td bgcolor="#000000">
                  <table width="100%" border="0" cellspacing="1" cellpadding="5">
                    <tr>
                      <td bgcolor="ffffff">
                        <table border="0" cellspacing="0" cellpadding="5" align="center">
<form action=index.php method=POST>
<input type=hidden name=op value="auth">
                          <tr>
                            <td class=sm align="right">E-mail :</td>
                            <td><input type="text" name="username" class=form size="20"></td>
                          </tr>
                          <tr>
                            <td class=sm align="right">Пароль: </td>
                            <td><input type="password" name="password" class=form size="20"></td>
                          </tr>
                          <tr>
                            <td>&nbsp;</td>
                            <td><input type="submit" value="Войти" class=knopka></td>
                          </tr>
</form>
                          <tr>
                            <td>&nbsp;</td>
                            <td class=sm><a href="index.php?op=forgot" class=maing>Забыли пароль?</a></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>