            <table width="100%" border="0" cellspacing="0" cellpadding="4" height="27">
              <tr> 
                <td bgcolor="479680" class=white>&nbsp;&nbsp;&nbsp;ВХОД ДЛЯ ОПТОВИКОВ</td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="20">
              <tr> 
                <td class=sm align="center">НОВЫЙ ПОЛЬЗОВАТЕЛЬ? <a href="index.php?op=newreg" class=r><b>Зарегистрироваться</b></a></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td bgcolor="DFDFDF"><img src="images/1p.gif" width="1" height="1"></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="20">
              <tr>
                <td class=sm align="center">ВХОД ДЛЯ ЗАРЕГИСТРИРОВАННЫХ ПОЛЬЗОВАТЕЛЕЙ:</td>
              </tr>
            </table>
            <table width="250" border="0" cellspacing="0" cellpadding="0" align="center">
              <tr>
                <td bgcolor="DFDFDF">
                  <table width="100%" border="0" cellspacing="1" cellpadding="5">
                    <tr>
                      <td bgcolor="F7F7F7">
                        <table border="0" cellspacing="0" cellpadding="5" align="center">
<form action=index.php method=POST>
<input type=hidden name=op value="auth">
                          <tr> 
                            <td class=sm align="right">Логин :</td>
                            <td><input type="text" name="username" class=form size="20"></td>
                          </tr>
                          <tr> 
                            <td class=sm align="right">Пароль: </td>
                            <td><input type="password" name="password" class=form size="20"></td>
                          </tr>
                          <tr> 
                            <td>&nbsp;</td>
                            <td><input type="submit" value="Войти" class=knopka></td>
                          </tr>
</form>
                          <tr> 
                            <td>&nbsp;</td>
                            <td class=sm><a href="index.php?op=forgot" class=r>Забыли пароль?</a></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
