                </tr>

          </table>



            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>

<!-- BEGIN list_menu -->
                      <td class=t align=center height=28 bgcolor=999999><b><a href="index.php?op={url}" class="w2">{shorttitle}</a></b></td>
<!-- END list_menu -->
                    </tr>
                  </table>

<!-- BEGIN title_bottom -->
      <table width="100%" border="0" cellspacing="0" cellpadding="4" height="27">
        <tr>
          <td bgcolor="FFFFFF" class=sm align="center">{title_bottom}</td>
        </tr>
      </table>
<!-- END title_bottom -->
<!-- homearts Belosnezhka  -->
 <table width="100%" border="0" cellspacing="0" cellpadding="1">
        <tr>
          <td bgcolor="FFFFFF"  align="center">
<a href="http://www.homearts.ru" target="_blank">
<img src="shedevr_bel_banner.gif" alt="Товары для рукоделия, вышивка, наборы для вышивания" border=0></a>
         </td>
        </tr>
<!-- homearts Belosnezhka xvost -->
<table width="100%" border="0" cellspacing="0" cellpadding="4">
        <tr>
          <td bgcolor="FFFFFF" height="31" align=center>
  <!--LiveInternet counter--><noindex><script type="text/javascript"><!--
document.write('<a href="http://www.liveinternet.ru/click" '+
'target=_blank><img src="http://counter.yadro.ru/hit?t52.1;r'+
escape(document.referrer)+((typeof(screen)=='undefined')?'':
';s'+screen.width+'*'+screen.height+'*'+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+';u'+escape(document.URL)+
';i'+escape('Жж'+document.title.substring(0,80))+';'+Math.random()+
'" alt="" title="LiveInternet: показано число просмотров и посетителей за 24 часа" '+
'border=0 width=88 height=31><\/a>')//--></script><!--/LiveInternet-->
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
var yaParams = {/*Здесь параметры визита*/};
</script>

<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript"></script>
<script type="text/javascript">
try { var yaCounter253781 = new Ya.Metrika({id:253781,
          webvisor:true,
          clickmap:true,
          accurateTrackBounce:true,params:window.yaParams||{ }});
} catch(e) { }
</script>
<noscript><div><img src="//mc.yandex.ru/watch/253781" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->


<!-- SpyLOG --><script src="http://tools.spylog.ru/counter2.2.js" type="text/javascript" id="spylog_code" counter="788200" ></script><noscript><a href="http://u7882.00.spylog.com/cnt?cid=788200&f=3&p=0" target="_blank"><img src="http://u7882.00.spylog.com/cnt?cid=788200&p=0&f=4" alt='SpyLOG' border='0'width=88 height=31 ></a> </noscript><!--/ SpyLOG --></noindex>
       

<noindex><a href="http://www.dvtech.ru" target="_blank">
<img src="http://www.newgame.ru/banners/88x31dvtech.gif" alt="DVD проигрыватели, Домашние кинотеатры, акустические системы" border=0 width=88 height=31></a>


<a href="http://www.newgame.ru/" target=_blank><img src="http://www.newgame.ru/banners/ng1.gif" alt="Сайт о видеоиграх и приставках" border=0 width=88 height=31></a>

<a href="http://www.yandex.ru/cy?base=0&host=www.shedevr.ru"><img src="http://www.yandex.ru/cycounter?www.shedevr.ru" width="88" height="31" alt="Яндекс цитирования" border="0"></a> </noindex>



   </td>
        </tr>
      </table>

 <td bgcolor="666666" width="1"><img src="images/1p.gif" width="1" height="1">
</td>
 <td background="images/verline.gif" width="5"><img src="images/1p.gif" width="7" height="1"></td>
  </tr>
</table>

</body>
</html>