


            <table width="100%" height=19 border="0" cellspacing="0" cellpadding="0">
              <tr height=19>
                <td width=4%> </td>
                <td width=6><img src=images/p_l.gif width=6 height=19></td>
                <td background=images/p.gif align=center valign=center><b><font color=#FFFFFF face="Verdana"><span style="font-size:11pt;">РЕЗУЛЬТАТ ОПРОСА</span></font></b></td>
                <td width=6><img src=images/p_r.gif width=6 height=19></td>
                <td width=4%> </td>
              </tr>
              <tr height=19><td></td>
              </tr>
            </table>
           <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="#ffffff" height=2></td>
              </tr>
              <tr>
                <td background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>
  <table width="100%" border="0" cellspacing="0" cellpadding="10">

                    <tr>

                      <td class=sm>
 <table width="100%" border="0" cellspacing="0" cellpadding="4">

                    <tr>

                      <td class=sm colspan=2>
                       <br>
                       <hr color=#cccccc size=1 noshade>
                       </td></tr>
                       <tr>
                       <td width=60% align=left valign=top>
                      <span style="font-size:10pt;"><font face="Verdana">
                      Цены на товары:</font></span>
                      </td>
                      <td valign=top>
                       <span style="font-size:10pt;"><font face="Verdana"><b>{worker}</b> %&nbsp;&nbsp;&nbsp;(</font></span>
                      <span style="font-size:10pt;"><font face="Verdana" color="ff0000">{worker1}</font></span>
                      <span style="font-size:10pt;"><font face="Verdana">)</font></span></td>
                      </tr>

                       <tr>
                       <td colspan=2>
                  <hr color=#cccccc size=1 noshade>
                      </td>
                    </tr>


                       <tr>
                       <td align=left valign=top>
                      <span style="font-size:10pt;"><font face="Verdana">
                      Быстрая доставка:</font></span>
                      </td>
                      <td valign=top>
                      <span style="font-size:10pt;"><font face="Verdana"> <b>{gosslug}</b> %&nbsp;&nbsp;&nbsp;(</font></span>
                       <span style="font-size:10pt;"><font face="Verdana" color="ff0000">{gosslug1}</font></span>
                      <span style="font-size:10pt;"><font face="Verdana">)</font></span>
                      </td></tr>

                       <tr>
                       <td colspan=2>
                  <hr color=#cccccc size=1 noshade>
                      </td>
                    </tr>

                      <tr>
                       <td align=left valign=top>
                      <span style="font-size:10pt;"><font face="Verdana">
                      Дизайн сайта:</font></span>
                       </td>
                       <td valign=top>
                       <span style="font-size:10pt;"><font face="Verdana"> <b>{manager}</b> %&nbsp;&nbsp;&nbsp;(</font></span>
                      <span style="font-size:10pt;"><font face="Verdana" color="ff0000">{manager1}</font></span>
                      <span style="font-size:10pt;"><font face="Verdana">)</font></span>
                       </td></tr>
                       <tr>
                       <td colspan=2>
                  <hr color=#cccccc size=1 noshade>
                      </td>
                    </tr>

                       <tr>
                       <td align=left valign=top>
                       <span style="font-size:10pt;"><font face="Verdana">

                      Удобная навигация:</font></span>
                      </td>
                      <td valign=top>
                        <span style="font-size:10pt;"><font face="Verdana"> <b>{student}</b> %&nbsp;&nbsp;&nbsp;(</font></span>
                       <span style="font-size:10pt;"><font face="Verdana" color="ff0000">{student1}</font></span>
                      <span style="font-size:10pt;"><font face="Verdana">)</font></span>

                      </td></tr>
                       <tr>
                       <td colspan=2>
                  <hr color=#cccccc size=1 noshade>
                      </td>
                    </tr>

                       <tr>
                       <td align=left valign=top>
                      <span style="font-size:10pt;"><font face="Verdana">
                      Другое:</font></span>
                       </td>
                        <td valign=top>
                       <span style="font-size:10pt;"><font face="Verdana"> <b>{other}</b> %&nbsp;&nbsp;&nbsp;(</font></span>
                       <span style="font-size:10pt;"><font face="Verdana" color="ff0000">{other1}</font></span>
                      <span style="font-size:10pt;"><font face="Verdana">)</font></span>
                       </td></tr>

                       <tr>
                       <td colspan=2>
                  <hr color=#cccccc size=1 noshade>
                      </td>
                    </tr>
                  </table>
                  </td>
                    </tr>
                  </table>