<html>
<head>
<title> {title} - shedevr.ru - интернет-магазин Видеоигры приставки диски стойки сумки </title>
<META NAME="Document-state" content="Dynamic">
<META NAME="Submission" content="http://www.shedevr.ru/">
<META NAME="robots" content="index,follow">
<META NAME="description" content="Интернет-магазин shedevr.ru предлагает-{description}<!-- BEGIN list_descript -->{name}{zapyataya}<!-- END list_descript -->{descriptid}<!-- BEGIN list_descript5 -->{name}{zapyataya5}<!-- END list_descript5 -->Видеоигры">
<META NAME="keywords" content="{key}<!-- BEGIN list_key -->{name}{zapyataya}<!-- END list_key -->{keyid}<!-- BEGIN list_key5 -->{name}{zapyataya5}<!-- END list_key5 -->Видеоигры приставки диски стойки сумки ">
<META NAME="title" content="{title}Интернет магазин shedevr.ru Видеоигры приставки диски стойки сумки ">

<link rel=stylesheet href="shedevr.css" type="text/css">

<script type="text/javascript" language="javascript">
<!--
function ValidSearchData() {
  var missinginfo = "";

  if(document.search.search.value == "") {
        missinginfo += "\n     - Введите строку поиска";
  }

  if (missinginfo != "") {
        alert(missinginfo);
        return false;
  } else return true;
}
-->
</script>
</head>

<body bgcolor="ffffff" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<table width="900" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr><noindex>
    <td background="images/verline.gif" width="6"><img src="images/1p.gif" width="7" height="1">




<!-- Rambler's Top100 code -->
<a href="http://top100.rambler.ru/top100/">
<img src="http://counter.rambler.ru/top100.cnt?601219" alt="" width=1 height=1 border=0></a>
<!-- Top100 code-->

<!--LiveInternet counter-->

<script language="JavaScript"><!--
document.write('<img src="http://counter.yadro.ru/hit?r'+
escape(document.referrer)+((typeof(screen)=='undefined')?'':
';s'+screen.width+'*'+screen.height+'*'+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+';u'+escape(document.URL)+
';i'+escape('Жж'+document.title)+';'+Math.random()+
'" width=1 height=1 alt="">')//--></script>

<!--/LiveInternet-->

<!-- SpyLOG f:0200 -->
<div STYLE="behavior:url(#default#clientCaps);" ID="MC"></div>
<script language="javascript"><!--
Mu="u3514.36.spylog.com";Md=document;Mnv=navigator;Mp=0;
Md.cookie="b=b";Mc=0;if(Md.cookie)Mc=1;Mrn=Math.random();
Mn=(Mnv.appName.substring(0,2)=="Mi")?0:1;Mt=(new Date()).getTimezoneOffset();
Mz="p="+Mp+"&rn="+Mrn+"&c="+Mc+"&tl=0&ls=0&ln=0&t="+Mt;
Mz+='&title='+escape(Md.title)+'&partname='+escape('main');
if(!Mn&&Mnv.userAgent.indexOf("Opera")<0&&Mnv.userAgent.indexOf("Mac")<0&&
(Mnv.appVersion.indexOf("MSIE 5")>-1||Mnv.appVersion.indexOf("MSIE 6")>-1))
{Mid="{D27CDB6E-AE6D-11CF-96B8-444553540000}";Midn="ComponentID";
Mfl=MC.getComponentVersion(Mid,Midn);Mct=MC.connectionType;Mz+='&fl='+Mfl+'&ct='+Mct;}
if(self!=top){Mfr=1;}else{Mfr=0;}Msl="1.0";
//-->
</script>
<script language="javascript1.1"><!--
Mpl="";Msl="1.1";Mj = (Mnv.javaEnabled()?"Y":"N");Mz+='&j='+Mj;
//-->
</script>
<script language="javascript1.2"><!--
Msl="1.2";Ms=screen;Mpx=(Mn==0)?Ms.colorDepth:Ms.pixelDepth;
Mz+="&wh="+Ms.width+'x'+Ms.height+"&px="+Mpx;
Mw=window;if(Mw.innerWidth){MwIW=Mw.innerWidth;MwIH=Mw.innerHeight;Mz+="&rwh="+MwIW+'x'+MwIH;}
else if(Md.body.clientWidth){MwIW=Md.body.clientWidth;MwIH=Md.body.clientHeight;Mz+="&rwh="+MwIW+'x'+MwIH;}
//--></script>
<script language="javascript1.3"><!--
Msl="1.3";//--></script><script language="javascript"><!--
My="";My+="<img src='http://"+Mu+"/cnt?cid=351436&"+Mz+"&sl="+Msl+"&r="+escape(Md.referrer)+"&fr="+Mfr+"&pg="+escape(window.location.href);
My+="' border=0 width=1 height=1 alt='SpyLOG'>";
Md.write(My);//--></script><noscript>
<img src="http://u3514.36.spylog.com/cnt?cid=351436&p=0" alt='SpyLOG' border='0' width=1 height=1 >
</noscript>
<!-- SpyLOG -->
<!--Rating@Mail.ru COUNTER--><script language="JavaScript" type="text/javascript"><!--
d=document;var a='';a+=';r='+escape(d.referrer)
js=10//--></script><script language="JavaScript1.1" type="text/javascript"><!--
a+=';j='+navigator.javaEnabled()
js=11//--></script><script language="JavaScript1.2" type="text/javascript"><!--
s=screen;a+=';s='+s.width+'*'+s.height
a+=';d='+(s.colorDepth?s.colorDepth:s.pixelDepth)
js=12//--></script><script language="JavaScript1.3" type="text/javascript"><!--
js=13//--></script><script language="JavaScript" type="text/javascript"><!--
d.write('<img src="http://top.list.ru/counter'+
'?id=828964;js='+js+a+';rand='+Math.random()+
'" height=1 width=1/>')
if(11<js)d.write('<'+'!-- ')//--></script><noscript><img
src="http://top.list.ru/counter?js=na;id=828964"
height=1 width=1 alt=""/></noscript><script language="JavaScript" type="text/javascript"><!--
if(11<js)d.write('--'+'>')//--></script><!--/COUNTER-->

</td> </noindex>
    <td bgcolor="#FFFFFF">
      <table width="888" border="0" cellspacing="0" cellpadding="0">
      <tr height=36><td background="images/v_l.gif" valign=bottom>биотуалеты(зел), автомобильные холодильники(оранж), складная мебель(голуб), надувные кровати(зел)</td>
      </tr>
        <tr><td><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://active.macromedia.com/flash4/cabs/swflash.cab#version=4,0,0,0" width="888">
            <param name="movie" value="../images/camp.swf">
            <param name="play" value="true">
            <param name="loop" value="true">
            <param name="quality" value="high">
            <embed src="camp.swf" play="true" loop="true" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" width="888"></embed>
            </object></td>
        </tr>
      </table>
      <table width="888" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width=178>
            <table width="90%" border=0 cellspacing=0 cellpadding=0 align=center height=40>
              <tr>
                <td align="center"><a href="index.php"><img src="images/hom.gif" border="0" alt="На главную"></a></td>
                <td align="center"><a href="index.php?op=cart"><img src="images/kart.gif" border="0" alt="Корзина"></a></td>
                <td align="center"><a href="index.php?op=contact"><img src="images/post.gif" border="0" alt="Обратная связь"></a></td>
                <td align="center"><a href="index.php?op=help"><img src="images/icon_faq.gif" border="0" alt="Помощь"></a></td>
              </tr>
            </table>
          </td>
          <td>
            <table border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="10"><img src="images/1p.gif" width="10" height="1"></td>
                <td class=t align="center">&nbsp;<a href="index.php?op=about" class=w>о компании</a>&nbsp;</td>
<!-- BEGIN unreg -->
                <td class=t align="center">&nbsp;<a href="index.php?op=reg" class=w>вход в магазин</a>&nbsp;</td>
                    <td class=t align="center">&nbsp;<a href="http://www.shedevr.ru/index.php?op=Optov" class=w>оптовикам</a>&nbsp;</td>
<!-- END unreg -->
<!-- BEGIN register -->
                <td class=t align="center">&nbsp;<a href="index.php?op=personal" class=w>персональная страница</a>&nbsp;</td>
                                <td bgcolor="E04D4D" width="1"><img src="images/1p.gif" width="1" height="1"></td>

<!-- END register -->


              </tr>
            </table>
          </td>
          <td align="right">

            <table border="0" cellspacing="0" cellpadding="0">
<form action="index.php" name="search" method="GET" onSubmit="return ValidSearchData();">
<input type=hidden name=op value=search>
              <tr>
                <td class=wn>поиск :&nbsp;&nbsp;&nbsp;</td>
                <td><input type="text" name="search" size="12" class=form></td>
                <td width="10"><img src="images/1p.gif" width="10" height="1"></td>
                <td>
                  <select name="type" size="1" class=form>
                    <option value="name">по названию</option>
                    <option value="brand">по бренду</option>
                  </select>
                </td>
                <td width="20" align="right"><input type=image src="images/search.gif" width="12" height="13" border="0"></td>
                <td><img src="images/1p.gif" width="10" height="1"></td>
                <td>&nbsp;</td>
              </tr>
</form>
            </table>

          </td>
        </tr>
      </table>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="images/1p.gif" width="1" height="1"></td>
        </tr>
      </table>

<!-- BEGIN termometr -->
            <table width="100%" border="0" cellspacing="0" cellpadding="4" height="27">
              <tr>
                <td bgcolor="FFFFFF" class=sm>&nbsp;&nbsp;&nbsp;{termometr}</td>
              </tr>
            </table>
<!-- END termometr -->

      <table width="800" border="0" cellspacing="0" cellpadding="0">
        <tr>