<html>
<head>
<title>{title}{supertitle}</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251"><meta http-equiv="Content-Language" content="ru">
<META NAME="Document-state" content="Dynamic">
<META NAME="Submission" content="http://www.shedevr.ru/">
<META NAME="robots" content="index,follow">
<meta name="description" content="Интернет-магазине Shedevr.ru предлагает наборы живописи по номерам, скрапбукинга, алмазной мозаики и вышивки от фирмы Белоснежка.Розничный магазин в Москве, цены от производителя, доставка по всей России почтой." />
<meta name="keywords" content="sega, dendy, картриджи, приставки, Белоснежка, алмазная вышивка, картины по номерам, раскраски по цифрам, алмазная живопись, живопись по номерам, скрапбукинг" />
<!-- <META NAME="keywords" content="{title}{supertitle}"> -->
<meta name="verify-v1" content="CQa2QX4xa+2kSweyjklCMgI6DmZ9lv9FLDTvcAz4Xrw=" />
<META HTTP-EQUIV="Page-Enter" CONTENT="blendTrans(Duration=0.5)"/>
<META HTTP-EQUIV="Page-Exit" CONTENT="blendTrans(Duration=0.5)"/>
<link rel=stylesheet href="shedevr.css" type="text/css">

<script type="text/javascript" language="javascript">
<!--
function ValidSearchData() {
  var missinginfo = "";

  if(document.search.search.value == "") {
        missinginfo += "\n     - Введите строку поиска";
  }

  if (missinginfo != "") {
        alert(missinginfo);
        return false;
  } else return true;
}
-->
</script>

</head>

<body bgcolor="ffffff" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<table width="900" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td background="images/verline.gif" width="5"><img src="images/1p.gif" width="7" height="1">
</td>
  <td bgcolor="666666" width="1"><img src="images/1p.gif" width="1" height="1">
</td>
    <td bgcolor="#FFFFFF">
       <table width="888" align=center cellspacing="0" cellpadding="0">
      <tr>
        <td bgcolor="ffffff" height=10>
        </td>
        </tr>
        </table>
      <table width="888" align=center cellspacing="0" cellpadding="0">
      <tr>
        <td bgcolor="ffffff" height=22 width=741 valign=top>

        </td>
        <td bgcolor="ffffff" valign=top>
        <a href="index.php?op=cart" title="Корзина"><img src="images/bask.gif" border=0></a>
        </td>
        <td bgcolor="ffffff" valign=top>
        <a href="index.php" title="Главная"><img src="images/dom.gif" border=0></a>
        </td>
        <td bgcolor="ffffff" valign=top>
        <a href="index.php?op=contact" title="Контакты"><img src="images/message.gif" border=0></a>
        </td>
        </tr>
        </table>
      <table width="888" align=center cellspacing="0" cellpadding="0">


       <tr>
        <td bgcolor="ffffff" valign=top width=318>
        <a href="index.php" title="Главная"><img src="images/logo.jpg" border=0></a></td>
        <td bgcolor="ffffff" valign=top>

        <table width=100% cellspacing="0" cellpadding="0">
      <tr>
        <td bgcolor="ffffff" colspan=2 align=left valign=top><img src="images/logo1.jpg" border=0></td>
        </tr>
        <tr>
        <td bgcolor="ffffff" align=center height=46 valign=top colspan=2>
        <span style="font-size:13pt"><font color=000000 face="Tahoma">
        Магазин "Видеоигры". м.Сокол, Волоколамское ш., д.1, к.1<br>Тел.: 8-499-158-65-11</font><a href="/sxema2.gif"> Карта проезда</a></span>
        </td>
        </tr>
         <tr>
        <td bgcolor="ffffff" align=left valign=top><a href=index.php?op=about><img src="images/about.jpg" border=0></a><img src="images/aboutline.jpg" border=0><!-- BEGIN unreg --><a href=index.php?op=reg><img src="images/enter.jpg" border=0></a><!-- END unreg --><!-- BEGIN register --><a href=index.php?op=reg><img src="images/exits.jpg" border=0></a><!-- END register --><img src="images/enterline.jpg" border=0><a href=#><img src="images/icq.jpg" border=0></a><img src="images/icqline.jpg" border=0>
        </td>
        <td bgcolor="ffffff" align=left valign=middle>
        <form action="index.php" name="search" method="GET" onSubmit="return ValidSearchData();">
<input type=hidden name=op value=search>
<input type="hidden" name=type value=name>
        <table cellspacing="0" cellpadding="0" align=left width=222>
      <tr>

        <td bgcolor="000000" align=left valign=top height=23 width=41><input type="image" src="images/searching.gif" border=0 alt="Поиск"></td>
        <td bgcolor="000000" align=left>
        <input type="text" name="search" size="19" class=form>
        &nbsp;
        </td>
        <td bgcolor="ffffff" align=left width=44>
        &nbsp;
        </td>
        </tr>
        </table>
        </form>
        </td>
        </tr>
        </table>
         </td>
        </tr>
        </table>
      <table width="100%" border="0" cellspacing="0" cellpadding="0" align=center>
              <tr>
      <td background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
     </tr></table>
     <!-- BEGIN termometr -->
            <table width="100%" border="0" cellspacing="0" cellpadding="4" height="27" align=center>
              <tr>
                <td bgcolor="f2f2f2" class=sm>&nbsp;&nbsp;&nbsp;{termometr}</td>
              </tr>
            </table>
         <table width="100%" border="0" cellspacing="0" cellpadding="4" align=center>
              <tr>
                <td bgcolor="#ffffff" height=2></td>
              </tr>
            </table>
         <table width="100%" border="0" cellspacing="0" cellpadding="4" align=center>
              <tr>
                <td background="images/point3.gif"></td>
              </tr>
            </table>
      <table width="100%" border="0" cellspacing="0" cellpadding="4" align=center>
              <tr>
                <td bgcolor="#ffffff" height=3></td>
              </tr>
            </table>

     <!-- END termometr -->
         <table width="100%" border="0" cellspacing="0" cellpadding="0" align=center>
              <tr>
                <td bgcolor="#ffffff" height=10></td>
              </tr>
            </table>
         <table width="888" border="0" cellspacing="0" cellpadding="0">
        <tr>