 <table width="100%" height=19 border="0" cellspacing="0" cellpadding="0">
              <tr height=19>
                <td width=4%> </td>
                <td width=6><img src=images/p_l.gif width=6 height=19></td>
                <td background=images/p.gif align=center valign=center><b><font color=#FFFFFF face="Verdana"><span style="font-size:11pt;">ПОВТОРНЫЙ ВВОД ДАННЫХ</span></font></b></td>
                <td width=6><img src=images/p_r.gif width=6 height=19></td>
                <td width=4%> </td>
              </tr>
              <tr height=19><td></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="#ffffff" height=2></td>
              </tr>
              <tr>
                <td background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="10">

                    <tr>

                      <td class=sm align=center><br>
       <span style="font-size:9pt;"><font face="Verdana"><b>Вы уже внесли данные!</b></font></span>
       </td></tr></table>