          <td valign="top" width="216" bgcolor="FFFFFF">
            <table width="100%" height=19 border="0" cellspacing="0" cellpadding="0">
              <tr>

                <td class=white align="center">
          <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                <b>КАТАЛОГ</b></span></font><p></td>

              </tr>
            </table>
<!-- BEGIN list -->
<!-- BEGIN cat_main_plus -->
            <table width="100%" border="0" cellspacing="0" cellpadding="1" bgcolor="#FFFFFF">
              <tr>
                <td width=3%> </td>
                <td width="24" align="center"><a href="index.php?op=catalog&pid={id}"><img src="images/leftmenu.jpg" alt="{name}" width="24" height="15" border="0"></a></td>
                <td class=smb><font class=leftmenus><a href="index.php?op=catalog&pid={id}" class=b title="{name}">{name}</a></font></td>
                <td width=7%> </td>
              </tr>
            </table>
<!-- END cat_main_plus -->

<!-- BEGIN cat_main_minus -->
            <table width="100%" border="0" cellspacing="0" cellpadding="1" bgcolor="#FFFFFF">
              <tr>
                <td width=3%> </td>
                <td width="24" align="center"><a href="index.php?op=catalog&pid={id}"><img src="images/leftmenu.jpg" class=b alt="{name}" width="24" height="15" border="0"></a></td>
                <td class=smb><font class=leftmenus><a href="index.php?op=catalog&pid={id}" class=b title="{name}">{name}</a></font></td>
                <td width=7%> </td>
              </tr>
            </table>
<!-- END cat_main_minus -->


<!-- BEGIN cat_submain -->
            <table width="100%" border="0" cellspacing="0" cellpadding="1" bgcolor="#FFFFFF">
              <tr>
                <td width=7%> </td>
                <td width="15" align="center"><img src="images/1p.gif" width="15" height="1"></td>
                <td class=sm><a href="index.php?op=catalog&cid={id}" class=b title="{name}">{name}</a></td>
                <td width=7%> </td>
              </tr>
            </table>
<!-- END cat_submain -->

<!-- BEGIN cat_separator -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF">
              <tr><td><img src="images/1p.gif" width="1" height="5"></td></tr>
              <tr><td>
              <table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF">
              <tr><td width="7%"></td><td bgcolor="cccccc"><img src="images/1p.gif" width="1" height="1"></td><td width="7%"></td></tr>
              </table>
              </td></tr>
              <tr><td><img src="images/1p.gif" width="1" height="5"></td></tr>
            </table>
<!-- END cat_separator -->
<!-- END list -->
            <table width="100%" border="0" cellspacing="0" cellpadding="5">
              <tr>
                <td align=center class=t><b>Контакты</b><br>
</td></tr><p><p><p>
<tr>
                        <td align=center class=t>
                    <a href=http://www.newgame.ru/us/shop.htm align=center class=сс>Магазин "Видеоигры"</a>
                        </td></tr>
<tr>
                        <td align=center class=t>
                    <a href="mailto:info@shedevr.ru" align=center class=сс>e-mail: info@shedevr.ru</a>
                        </td></tr>
                        <tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF">
<td align="center" valign="bottom"><span class="sm"><a class=сс href="Интернет-магазин shedevr.ru" onClick="window.external.addFavorite('http://www.shedevr.ru','Интернет-магазин shedevr.ru'); return false;">Добавить в избранное</a></td>
</tr>
<tr>
<td valign="top" align="center" class=sm>
<br><a class=сс href="http://www.shedevr.ru/"
    onclick="this.style.behavior='url(#default#homepage)';this.setHomePage('http://www.shedevr.ru'); return false;"
    style="BEHAVIOR: url(#default#homepage)">Сделать стартовой</a></td>
</tr>
           </table><br>

                  </td>

          <td background="images/point.gif" width="4" bgcolor="ffffff"><img src="images/1p.gif" width="4" height="1"></td>
          <td width="449" valign="top">