          <td valign="top" width="220" bgcolor="F9F9F9">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width=6><img src=images/p_l.gif width=6 height=19></td>
                <td background=images/p.gif align=center valign=center><b>каталог</b></td>
                <td width=6><img src=images/p_r.gif width=6 height=19></td>
              </tr>
              <tr height=19><td></td>
              </tr>
            </table>
<!-- BEGIN list -->
<!-- BEGIN cat_main_plus -->
            <table width="100%" border="0" cellspacing="0" cellpadding="1" bgcolor="#FFFFFF">
              <tr>
                <td width="15" align="center"><a href="index.php?op=catalog&pid={id}"><img src="images/plus.gif" width="9" height="9" border="0"></a></td>
                <td class=smb><a href="index.php?op=catalog&pid={id}" class=b>{name}</a></td>
              </tr>
            </table>
<!-- END cat_main_plus -->

<!-- BEGIN cat_main_minus -->
            <table width="100%" border="0" cellspacing="0" cellpadding="1" bgcolor="#FFFFFF">
              <tr>
                <td width="15" align="center"><a href="index.php?op=catalog&pid={id}"><img src="images/minus.gif" width="9" height="9" border="0"></a></td>
                <td class=smb><a href="index.php?op=catalog&pid={id}" class=b>{name}</a></td>
              </tr>
            </table>
<!-- END cat_main_minus -->


<!-- BEGIN cat_submain -->
            <table width="100%" border="0" cellspacing="0" cellpadding="1" bgcolor="#FFFFFF">
              <tr>
                <td width="15" align="center"><img src="images/1p.gif" width="15" height="1"></td>
                <td class=sm><a href="index.php?op=catalog&cid={id}" class=b>{name}</a></td>
              </tr>
            </table>
<!-- END cat_submain -->

<!-- BEGIN cat_separator -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF">
              <tr><td><img src="images/1p.gif" width="1" height="5"></td></tr>
              <tr><td bgcolor="AD0101"><img src="images/1p.gif" width="1" height="1"></td></tr>
              <tr><td><img src="images/1p.gif" width="1" height="5"></td></tr>
            </table>
<!-- END cat_separator -->
<!-- END list -->

            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td background="images/wtrihback.gif"><img src="images/1p.gif" width="1" height="12"></td>
              </tr>
            </table>

            <table width="100%" border="0" cellspacing="0" cellpadding="5">
              <tr>
                <td align=center class=t><b>Тел.: (499) 158-6511 </b><br>
</td></tr><p>
<tr>
                        <td align=center class=t>
                    <a href="mailto:info@shedevr.ru" align=center class=t>e-mail: info@shedevr.ru</a>
                        </td></tr>
                        <tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#F9F9F9">
<td align="left" valign="bottom"><span class="sm"><a href="Интернет-магазин shedevr.ru" onClick="window.external.addFavorite('http://www.shedevr.ru','Интернет-магазин shedevr.ru'); return false;">Добавить в избранное</a></td>
</tr>
<tr>
<td valign="top" align="left"><span class="sm">
<a href="http://www.shedevr.ru/"
    onclick="this.style.behavior='url(#default#homepage)';this.setHomePage('http://www.shedevr.ru'); return false;"
    style="BEHAVIOR: url(#default#homepage)">Сделать стартовой</a></td>
</tr>
           </table>

                  </td>

          <td width="1" bgcolor="DDDDDD"><img src="images/1p.gif" width="1" height="1"></td>
          <td width="383" valign="top">
