<table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>

                <td bgcolor="ffffff" class=white align="center">
                <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                <b>КАТАЛОГ ССЫЛОК</b></font></span></td>

              </tr>
            </table><br>
 <table width="95%" border="0" cellspacing="0" cellpadding="0" align=center>
              <tr>
                <td bgcolor="#ffffff" align=center>
  <hr color="000000" size=1 noshade>

  <span style="font-size:9pt"><font face="Verdana" color="000000"><b>Раздел: {namecat}</b></span></font>

    <hr color="000000" size=1 noshade>
               <br><br>
                </td>
                </tr>
       <tr>
                <td bgcolor="#ffffff" class=sm>

  <!-- BEGIN list_cat -->
   {visuallinks}
   <hr color="cccccc" size=2 noshade>
  <!-- END list_cat -->
  <!-- BEGIN no_list_cat -->
 <center><span style="font-size:9pt"><font face="Verdana" color="000000">В этой категории нет ссылок</span></font></center><br><br>
  <!-- END no_list_cat -->
                </td>
                </tr>
    <tr>
                <td bgcolor="#ffffff" align=center>
   {hr}
   <span style="font-size:9pt"><font face="Verdana" color="000000">Страницы:&nbsp;&nbsp;</span></font>
   <!-- BEGIN list_nav -->
   {s}
   <!-- END list_nav -->
   {hr1}

                </td>
                </tr>
     <tr>
                <td bgcolor="#ffffff" align=center><br>
      <form action=index.php method=GET>

      <input type=hidden name=op value=addlinks>
      <input type=submit name=submit value="Добавить ресурс" class=knopka>
      </form>
      <span style="font-size:10pt"><font face=Verdana><a href="index.php?op=linkscatalog">Вернуться к списку категорий</a></span></font>
        <br><br>
          </td></tr>
                </table>