
    <table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>
                <td bgcolor="ffffff" class=white align="center">
                <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                <b>ДОБАВЛЕНИЕ ССЫЛКИ</b></font></span></td>
              </tr>
            </table><br><br>

  <table width="95%" border="0" cellspacing="0" cellpadding="0" align=center>

                <tr>
                <td bgcolor="#ffffff" align=center>
<span style="font-size:9pt"><font face="Verdana" color="000000"><b>Ваша заявка принята!</b><br><br>
В ближайшее время менеджер рассмотрит заявку и свяжется с Вами.
</span></font><br><br>
                </td></tr>

    <tr>
                <td bgcolor="#ffffff" align=center><br>
      <form action=index.php method=GET>

      <input type=hidden name=op value=linkscatalog>
       <hr color=000000 size=1 noshade>
      <input type=submit name=submit value="К списку категорий" class=knopka>
       <hr color=000000 size=1 noshade>
      </form>
          </td></tr>
         </table>