<table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>
                <td bgcolor="ffffff" class=white align="center">
                <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                <b>КАТАЛОГ ССЫЛОК</b></font></span></td>
              </tr>
</table><br>
 <table width="84%" height="400" border="0" align=center cellpadding="0" cellspacing="0">
              <tr>
                <td bgcolor="#ffffff">
  <hr color="cccccc" size=1 noshade>
  <!-- BEGIN list_cat -->
  <span style="font-size:8pt"><font face="Verdana" color="0057a9"><b>&bull;&nbsp;<a href="index.php?op=linkscatalog&page=1&idcat={idcat}">{namecat}</a></b></span></font><br>
  <!-- END list_cat -->
    <hr color="cccccc" size=1 noshade>
                </td>
   </tr>
   <tr>
     <td height="342" align=center bgcolor="#ffffff" class="sm"><br>
      <form action=index.php method=GET>

      <input type=hidden name=op value=addlinks>
      <input type=submit name=submit value="Добавить ресурс" class=knopka>
      </form>
          <p></p>
          <span class="smb">НАША ССЫЛКА
          </form>
          </span>
          <form name="form1" method="post" action="">
  <textarea name="textarea" cols="50" rows="5"><!-- Shedevr.ru--> <a href="http://www.shedevr.ru" target=_blank> <img src="http://www.newgame.ru/banners/shedevr_banner_88x31_animated.gif" width=88 height=31 border=0 alt="Интернет магазин электроники Shedevr.Ru. Игры и игровые приставки. Игровые и CD-аксессуары. DVD проигрыватели и акустические системы."></a> <a href="http://www.Shedevr.ru" target=_blank> Интернет магазин электроники Shedevr.Ru. Игры и игровые приставки. Игровые и CD-аксессуары. DVD проигрыватели и акустические системы.</a> <!--end link shedevr.ru-->
  </textarea>
</form> </p></td>
   </tr>
</table>