<!-- BEGIN spec_pred_nah -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28">
              <tr>
                <td width=25> </td>
                <td width=9></td>
                <td  bgcolor="ffffff" align="center">
                <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                <b>Спецпредложения</b></span></font></td>

                <td width=9></td>
                <td width=25> </td>
              </tr>
            </table>

            <table width="448" border="0" cellspacing="0" cellpadding="0">

<!-- BEGIN main_second -->
              <tr>

<!-- BEGIN list_spec1 -->

                <td width="224" valign=top>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                        <table width="200" border="0" cellspacing="0" cellpadding="2" align="center">
                    <tr>
                      <td class=tb>
                                                <a class=maing href="index.php?id={id}">{name} {mark}</a>&nbsp;
                                               </td>
                    </tr>
                    <tr>
                      <td valign="middle" align=center height=150>
                                                <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                          </td>
                                        </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                                        <tr>
                     <td class=green nowrap><a class=maing href="index.php?id={id}">{price} руб.</a></td>
                    </tr>
              <tr>
                <td class=sm><a class=maing href="index.php?id={id}">{description}</a><br>
                 <HR size="1" color="000000" noshade>
                <a href="index.php?op=catalog&cid={cid}" class=maing>Показать все товары группы - {imya}</a>
                </td>
              </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                  </table>

                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>

<!-- END list_spec1 -->
<!-- BEGIN no_list_spec1 -->
                <td width="224">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END no_list_spec1 -->

                <td background="images/point2.gif" width="1" bgcolor="ffffff"><img src="images/1p.gif" width="1" height="1"></td>

<!-- BEGIN list_spec2 -->
                <td width="224" valign=top>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                        <table width="200" border="0" cellspacing="0" cellpadding="2" align="center">
                    <tr>
                      <td class=tb>
                                                <a class=maing href="index.php?id={id}" class=r>{name} {mark}</a>&nbsp;
                                                </td>
                    </tr>
                    <tr>
                      <td valign="middle" align=center height=150>
                                                <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                          </td>
                                        </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                                        <tr>
                     <td class=green nowrap><a class=maing href="index.php?id={id}">{price} руб.</a></td>
                    </tr>
              <tr>
                <td class=sm><a href="index.php?id={id}" class=maing>{description}</a><br>
               <HR size="1" color="000000" noshade>
               <a href="index.php?op=catalog&cid={cid}" class=maing>Показать все товары группы - {imya}</a>
                </td>
              </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                  </table>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END list_spec2 -->
<!-- BEGIN no_list_spec2 -->
                <td width="224">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END no_list_spec2 -->
              </tr>
              <tr>
                <td colspan="3" background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
<!-- END main_second -->
              <!--<tr>
                <td colspan="3">
                  <table width="100%" border="0" cellspacing="0" cellpadding="5">
                    <tr>
                      <td class=smb bgcolor="F0F0F0">&nbsp;&nbsp;<a href="index.php?op=spec" class=b>все спецпредложения </a></td>
                    </tr>
                  </table>
                </td>
              </tr>
              <tr>
                <td colspan="3" bgcolor="DCDDDC"><img src="images/1p.gif" width="1" height="1"></td>
              </tr>
            </table>-->
<!-- END spec_pred_nah -->
                <table width="100%" border="0" cellspacing="0" cellpadding="4" align=center>
              <tr>
                <td  bgcolor="#ffffff" height=2></td>
              </tr>
            </table>
               <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28">
              <tr>
                <td width=20> </td>
                <td width=9></td>
                <td bgcolor="ffffff" class=white align="center">
                <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
<a href="http://www.newgame.ru/us/shop.htm" target="_blank">
<img border="0" src="http://www.newgame.ru/shop_banner.gif" alt="ремонт игровых приставок"></a>
                <b>Новые поступления</b></span></font>

                </td>
                <td width=9></td>
                <td width=20> </td>
              </tr>
            </table>
               <table width="448" border="0" cellspacing="0" cellpadding="0">

              <tr>
                <td colspan=3 width="448">
                 <table width="100%" border="0" cellspacing="0" cellpadding="4" align=center>
              <tr>
                <td  bgcolor="#ffffff" height=2></td>
              </tr>
            </table>





                </td>
              </tr>


<!-- BEGIN main_first -->
              <tr>
<!-- BEGIN list_new -->
                <td valign=top>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                        <table width="200" border="0" cellspacing="0" cellpadding="2" align="center">
                    <tr>
                      <td class=tb>
                                                <a href="index.php?id={id}" class=maing>{name} {mark}</a>&nbsp;
                                          </td>
                    </tr>
                    <tr>
                      <td valign="middle" align=center height="157">
                                                <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                          </td>
                                        </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                                        <tr>
                     <td class=green nowrap><a class=maing href="index.php?id={id}">{price} руб.</a></td>
                    </tr>
              <tr>
                <td class=sm><a href="index.php?id={id}" class=maing>{description}</a><br>
               <HR size="1" color="000000" noshade>
              <a href="index.php?op=catalog&cid={cid}" class=maing>Показать все товары группы - {imya}</a>
                </td>
              </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                  </table>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END list_new -->
<!-- BEGIN no_list_new -->
                <td>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END no_list_new -->

                <td background="images/point2.gif" width="1" bgcolor="ffffff"><img src="images/1p.gif" width="1" height="1"></td>

<!-- BEGIN list_season -->
                <td valign=top>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                        <table width="200" border="0" cellspacing="0" cellpadding="2" align="center">
                    <tr>
                      <td class=tb>
                                                <a href="index.php?id={id}" class=maing>{name} {mark}</a>&nbsp;
                                               </td>
                    </tr>
                    <tr>
                      <td valign="middle" align=center height="157">
                                                <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                          </td>
                                        </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                                        <tr>
                     <td class=green nowrap><a class=maing href="index.php?id={id}">{price} руб.</a></td>
                    </tr>
              <tr>
               <td class=sm><a href="index.php?id={id}" class=maing>{description}</a><br>
               <HR size="1" color="000000" noshade>
                <a href="index.php?op=catalog&cid={cid}" class=maing>Показать все товары группы - {imya}</a>
               </td>
              </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="2"></td>
                            </tr>
                  </table>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END list_season -->
<!-- BEGIN no_list_season -->
                <td>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="2"></td></tr>
                  </table>
                </td>
<!-- END no_list_season -->

              </tr>
              <tr>
                <td colspan="3" background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
<!-- END main_first -->


            </table>