            <table width="383" border="1" cellspacing="0" cellpadding="0">

<!-- BEGIN spec -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>
                <td width=25> </td>
                <td width=9><img src=images/p1_l.gif width=9 height=19></td>
                <td bgcolor="007646" class=white align="center">—œ≈÷œ–≈ƒÀŒ∆≈Õ»ﬂ</td>
                <td width=9><img src=images/p1_r.gif width=9 height=19></td>
                <td width=25> </td>
              </tr>
            </table>
<!-- END spec -->

<!-- BEGIN new -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>
                <td width=25> </td>
                <td width=9><img src=images/p1_l.gif width=9 height=19></td>
                <td bgcolor="007646" class=white align="center">¬—≈ Õ¿ œ» Õ» </td>
                <td width=9><img src=images/p1_r.gif width=9 height=19></td>
                <td width=25> </td>
              </tr>
            </table>
<!-- END new -->

<!-- BEGIN season -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>
                <td width=25> </td>
                <td width=9><img src=images/p1_l.gif width=9 height=19></td>
                <td bgcolor="007646" class=white align="center">ÕŒ¬»Õ »</td>
                <td width=9><img src=images/p1_r.gif width=9 height=19></td>
                <td width=25> </td>
              </tr>
            </table>
<!-- END season -->

            <table width="383" border="0" cellspacing="0" cellpadding="0">

<!-- BEGIN main_second -->
              <tr>

<!-- BEGIN list_spec1 -->
                <td width="191" valign=top>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="10"></td></tr>
                  </table>

                        <table width="170" border="0" cellspacing="0" cellpadding="2" align="center">
                    <tr>
                      <td class=tb>
                                                <a href="index.php?{id}" class=r>{name}<br>{mark}</a>&nbsp;
                                                <a href="index.php?{id}" class=r><img src="images/arrow_red.gif" width="7" height="7" border="0"></a></td>
                    </tr>
                    <tr>
                      <td valign="top">
                                                <a href="index.php?{id}" class=r><img src="{photo_small}" alt="{name}<br>{mark}" {wh} border="0"></a>
                                          </td>
                                        </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="10"></td>
                            </tr>
                                        <tr>
                      <td class=green nowrap>{price} Û·.</td>
                    </tr>
                                        <tr>
                      <td class=sm>{description}</td>
                    </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="10"></td>
                            </tr>
                  </table>

                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="10"></td></tr>
                  </table>
                </td>
<!-- END list_spec1 -->
<!-- BEGIN no_list_spec1 -->
                <td width="191">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="10"></td></tr>
                  </table>
                </td>
<!-- END no_list_spec1 -->

                <td bgcolor="DCDDDC"><img src="images/1p.gif" width="1" height="1"></td>

<!-- BEGIN list_spec2 -->
                <td width="191" valign=top>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="10"></td></tr>
                  </table>

                        <table width="170" border="0" cellspacing="0" cellpadding="2" align="center">
                    <tr>
                      <td class=tb>
                                                <a href="index.php?{id}" class=r>{name}<br>{mark}</a>&nbsp;
                                                <a href="index.php?{id}" class=r><img src="images/arrow_red.gif" width="7" height="7" border="0"></a></td>
                    </tr>
                    <tr>
                      <td valign="top">
                                                <a href="index.php?{id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                          </td>
                                        </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="10"></td>
                            </tr>
                                        <tr>
                      <td class=green nowrap>{price} Û·.</td>
                    </tr>
                                        <tr>
                      <td class=sm>{description}</td>
                    </tr>
                            <tr>
                                <td><img src="images/1p.gif" width="1" height="10"></td>
                            </tr>
                  </table>

                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="10"></td></tr>
                  </table>
                </td>
<!-- END list_spec2 -->
<!-- BEGIN no_list_spec2 -->
                <td width="191">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr><td><img src="images/1p.gif" width="1" height="10"></td></tr>
                  </table>
                </td>
<!-- END no_list_spec2 -->
              </tr>

              <tr>
                <td colspan="3" bgcolor="DCDDDC"><img src="images/1p.gif" width="1" height="1"></td>
              </tr>
<!-- END main_second -->
            </table>