<table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>
                <td width=25> </td>
                <td width=9><img src=images/p1_l.gif width=9 height=19></td>
                <td bgcolor="003E76" class=white align="center">НЕСУЩЕСТВУЮЩАЯ СЕКРЕТНАЯ СТРАНИЦА</td>
                <td width=9><img src=images/p1_r.gif width=9 height=19></td>
                <td width=25> </td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="#ffffff" height=2></td>
              </tr>
              <tr>
                <td background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>


 <table border="0" cellpadding="0" cellspacing="0" align="center" width="95%">
    <tr>
        <td class=t1 bgcolor="#ffffff"><BR><BR>
   <center><font face="Verdana"><b>ОШИБКА 404 - Секретная страница!</b></font></center><br><br>
  <b>Страница которую Вы видите очень секретная и реально несуществующая.</b>
 <hr color=#000000 size=1 noshade>
  Давайте разберемся почему Вы здесь!<br>
  Скорее всего Вы пришли сюда по очень секретной и несуществующей ссылке,
  или эта ссылка существовала раньше и не была секретной, а теперь стала очень секретной и реально несуществующей.<br><br>

  Большая просьба если Вы нашли такую ссылку, сообщите нашему крутому веб-мастеру
  <a href=mailto:info@shedevr.ru>info@shedevr.ru</a><br>
  Он будет Вам очень благодарен!<br><br>
  Есть другой способ попасть сюда:<br>
  набрать в строке броузера очень секретный адрес:<br>
   <b>www.shedevr.ru/ыфвывы</b><br>
    или<br>
    <b>www.shedevr.ru/asaddsf</b> и тд.<br><br>
    Теперь когда мы разобрались почему Вы здесь, я предлагаю воспользоваться
    реальной и общедоступной ссылкой:
    <a href="http://shedevr.ru">www.shedevr.ru</a><br><br>
     <hr color=#000000 size=1 noshade>
     <b>P.S.</b> Не рассказывайте об этой секретной ссылке никому, чтобы избежать попадания сюда посторонних людей :)
        </td>
    </tr>
    <tr>
    <td  class=t1 bgcolor="#ffffff">
    <br><br>
    <center><b>Нажмите на баннер и будет счастье!!!<br>
    </b></center><br>
    <center><a href=index.php><img src="ban.gif" border="0"></a></center>
     </td>
     </tr>
</table>
