            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>
                <td bgcolor="ffffff" class=white align="center">
                 <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                <b>СПАСИБО ЗА ЗАКАЗ</b><font></span></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="#ffffff" height=2></td>
              </tr>
              <tr>
                <td background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="10">
              <tr>
                <td class=sm>
                  <p><b>Заказ успешно оформлен!</b></p>
                  <p>Копия заказа отправлена на указанный Вами E-mail. Вам в течении
                    дня позвонит оператор для подтверждения заказа. </p>
                  <p>Спасибо за сотрудничество!</p>
                  </td>
              </tr>
            </table>
            <table width="95%" border="0" cellspacing="0" cellpadding="0" align="center">
              <tr>
                <td bgcolor="#000000">
                  <table width="100%" border="0" cellspacing="1" cellpadding="5">
                    <tr>
                      <td bgcolor="ffffff">
                        <table border="0" cellspacing="0" cellpadding="5" align="center" width="100%">
                          <tr>
                            <td class=sm align="center"><b>Заказ N {zid} от {date_zid}</b></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><img src="images/1p.gif" width="1" height="15"></td>
              </tr>
            </table>
            <table width="95%" border="0" cellspacing="0" cellpadding="0" align="center">
              <tr>
                <td bgcolor="#000000">
                  <table width="100%" border="0" cellspacing="1" cellpadding="5">
                    <tr>
                      <td bgcolor="ffffff">
                        <table border="0" cellspacing="0" cellpadding="5" align="center" width="100%">


                          <tr>
                            <td class=sm valign="top" align="right" width="50%">ФИО или название организации :</td>
                            <td class=sm valign="top">{fio}</td>
                          </tr>

                          <tr>
                            <td class=sm valign="top" align="right" width="50%">Страна :</td>
                            <td class=sm valign="top">{country}</td>
                          </tr>
                          <tr>
                            <td class=sm valign="top" align="right" width="50%">Город :</td>
                            <td class=sm valign="top">{city}</td>
                          </tr>
                          <tr>
                            <td class=sm valign="top" align="right" width="50%">Ближайшее метро :</td>
                            <td class=sm valign="top">{metro}</td>
                          </tr>
                          <tr>
                            <td class=sm valign="top" align="right" width="50%">Телефон :</td>
                            <td class=sm valign="top">{phone}</td>
                          </tr>
                          <tr>
                            <td class=sm valign="top" align="right" width="50%">Адрес доставки :</td>
                            <td class=sm valign="top">{address}</td>
                          </tr>
                          <tr>
                            <td class=sm valign="top" align="right" width="50%">Номер дисконтаной карты :</td>
                            <td class=sm valign="top">{discont}</td>
                          </tr>
                          <tr>
                            <td class=sm valign="top" align="right" width="50%">Желаемая дата доставки :</td>
                            <td class=sm valign="top">{date_delivery}</td>
                          </tr>
                          <tr>
                            <td class=sm valign="top" align="right" width="50%">Желаемое время доставки :</td>
                            <td class=sm valign="top">{time_delivery}</td>
                          </tr>
                          <tr>
                            <td class=sm valign="top" align="right" width="50%">Способ оплаты: </td>
                            <td class=sm valign="top">Наличными курьеру</td>
                          </tr>
                          <tr>
                            <td class=sm valign="top" align="right" width="50%">Дополнительно :</td>
                            <td class=sm valign="top">{description}</td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="10">
              <tr>
                <td class=sm align="center">
                  <p>Доставка по Москве в течении 1-3 дней от момента оформления
                    заказа. </p>
                  </td>
              </tr>
            </table>