                  </td>
          <td width="1" bgcolor="DDDDDD"><img src="images/1p.gif" width="1" height="1"></td>

          <td valign="top" width="191" bgcolor="#FFFFFF">

<!-- BEGIN spec -->
            <table width="100%" border="0" cellspacing="0" cellpadding="4" height="27">
              <tr>
                <td bgcolor="D30000" class=white>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td class=white>&nbsp;%&nbsp;ТОВАРЫ СО СКИДКАМИ&nbsp;%</td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>

<!-- BEGIN list_spec -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
            </table>
            <table width="170" border="0" cellspacing="0" cellpadding="2" align="center">
              <tr>
                <td class=tb>
                                  <a href="index.php?id={id}" class=r>{name}</a>&nbsp;&nbsp;
                  <a href="index.php?spec={id}" class=r><img src="images/arrow_red.gif" width="7" height="7" border="0"></a>
                                </td>
              </tr>
              <tr>
                <td valign="top">
                                  <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                </td>
              </tr>
              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
              <tr>
                <td class=green nowrap>{price} руб.</td>
              </tr>

              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="DFDFDF"><img src="images/1p.gif" width="1" height="1"></td>
              </tr>
            </table>
<!-- END list_spec -->

            <table width="100%" border="0" cellspacing="0" cellpadding="5">
              <!-- <tr>
                <td class=smb bgcolor="F0F0F0">&nbsp;&nbsp;<a href="index.php?op=spec" class=b>все спецпредложения</a></td>
              </tr> -->
            </table>
<!-- END spec -->


<!-- BEGIN season -->
            <table width="100%" border="0" cellspacing="0" cellpadding="4" height="27">
              <tr>
                <td bgcolor="D30000" class=white>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td class=white>&nbsp;&nbsp;&nbsp;ХИТЫ ПРОДАЖ</td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>

<!-- BEGIN list_season -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
            </table>
            <table width="170" border="0" cellspacing="0" cellpadding="2" align="center">

              <tr>
                <td class=tb>
                                  <a href="index.php?id={id}" class=r>{name}</a>&nbsp;&nbsp;
                  <a href="index.php?id={id}" class=r><img src="images/arrow_red.gif" width="7" height="7" border="0"></a>
                                </td>
              </tr>
              <tr>
                <td valign="top">
                                  <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                </td>
              </tr>
              <tr>
                <td class=green>{price} руб.</td>
              </tr>

                          <tr>
                                <td><img src="images/1p.gif" width="1" height="10"></td>
                          </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="DFDFDF"><img src="images/1p.gif" width="1" height="1"></td>
              </tr>
            </table>
<!-- END list_season -->

            <table width="100%" border="0" cellspacing="0" cellpadding="0">
           <!--   <tr>
                <td class=smb bgcolor="F0F0F0">&nbsp;&nbsp;<a href="index.php?op=season" class=b> <!--все новинки--> </a></td>
              </tr>
            </table>
<!-- END season -->


<!-- BEGIN news -->
            <table width="100%" border="0" cellspacing="0" cellpadding="4" height="27">
              <tr>
                <td bgcolor="D30000" class=white>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td class=white>&nbsp;&nbsp;&nbsp;НОВИНКИ</td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
<!-- BEGIN list_news -->
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
            </table>
            <table width="170" border="0" cellspacing="0" cellpadding="2" align="center">
              <tr>
                <td class=tb>
                                  <a href="index.php?id={id}" class=r>{name}</a>&nbsp;&nbsp;
                                  <a href="index.php?id={id}" class=r><img src="images/arrow_red.gif" width="7" height="7" border="0"></a>
                                </td>
              </tr>
              <tr>
                <td valign="top">
                                  <a href="index.php?id={id}" class=r><img src="{photo_small}" {wh} border="0"></a>
                                </td>
              </tr>
                          <tr>
                <td class=green>{price} руб.</td>
              </tr>

                          <tr>
                                <td><img src="images/1p.gif" width="1" height="10"></td>
                          </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="DFDFDF"><img src="images/1p.gif" width="1" height="1"></td>
              </tr>
            </table>
<!-- END list_news -->

            <table width="100%" border="0" cellspacing="0" cellpadding="5">
              <tr>
                                <td class=smb bgcolor="F0F0F0">&nbsp;&nbsp;<a href="index.php?op=new" class=b><!--все подарки--></a></td>
                          </tr>
            </table>
<!-- END news -->

          </td>