          <TABLE border="0" cellpadding="0" cellspacing="0" width="563">
    <TR>
    <TD ALIGN=center width="263" height="170" rowspan="2">
        <img src="images/{photos}" border="0">
                          </TD>
    <TD class=name width="300" height="85">

 {name}
                         </TD></TR>
    <TR>
    <TD VALIGN=top class=model width="300" HEIGHT="85">

{mark}
:
{model}

                          </TD></TR>
    <TR>
     <TD class=descript width="563" colspan="2">
 {description}

                               </TD></TR>
    <TR>
    <TD class=cen width="563" height="34" colspan="2">
           ÷ена: <FONT color=red>{price}</FONT>р.
                      </TD></TR></TABLE></BODY></HTML>