            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="19">
              <tr>

                <td bgcolor="ffffff" class=white align="center">
                <span style="font-size:10pt"><font color="3879B3" face="Tahoma">
                <b>РЕЗУЛЬТАТ ПОИСКА</b></font></span></td>

              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><img src="images/1p.gif" width="1" height="10"></td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="5">
              <tr>
                <td class=sm>
<div class=t>Результат поиска строки "{search}": найдено совпаденией - {num} </div>
                                </td>
              </tr>
            </table>

            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="3" background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>


<!-- BEGIN list -->
            <table width="100%" border="0" cellspacing="0" cellpadding="7">
              <tr>
                <td class=sm><img src="images/arrow_green.gif" width="7" height="7">
                  &nbsp;&nbsp;<a href="index.php?id={id}" class=t><b>{name} {mark} {model}</b></a> <br>                                {description}<br>
<!--                                <font size=-1 color=grey>{site}?id={id}</font> -->
                                </td>
              </tr>
            </table>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="3" background="images/point3.gif" height="1" bgcolor="ffffff"><img src="images/1p.gif" height="1"></td>
              </tr>
            </table>
<!-- END list -->

<!-- BEGIN no_list -->

<!-- END no_list -->
<table width=100% cellpadding=12 cellspacing=0>
  <tr>
        <td align=right class=t valign=middle>
{nav_bar}
        </td>
  </tr>
</table>
</div>
